# Complete Zahuyach configuration example
# All settings are optional except the main ones in [site] and [build] sections

# ===== SITE SETTINGS =====
[site]
# Required settings
title = "Мой блог"                                  # Site title
description = "Технический блог о программировании" # Site description
author = "Иван Иванов"                              # Site author
base_url = "https://example.com"                    # Base site URL (without trailing slash)

# Optional settings
language = "ru"            # Site language (default: "ru")
timezone = "Europe/Moscow" # Timezone (default: "UTC")
email = "ivan@example.com" # Author's email

# Social networks (all optional)
[site.social]
github = "https://github.com/username"
twitter = "https://twitter.com/username"
linkedin = "https://linkedin.com/in/username"
email = "ivan@example.com"                     # Can be different from main email
mastodon = "https://mastodon.social/@username"
youtube = "https://youtube.com/@username"
instagram = "https://instagram.com/username"
facebook = "https://facebook.com/username"

# ===== BUILD SETTINGS =====
[build]
# Required settings
output_dir = "dist"         # Output directory for built site
content_dir = "content"     # Posts directory
static_dir = "static"       # Static files directory
templates_dir = "templates" # Templates directory

# Optional settings
clean_output = true     # Clean output directory before build (default: true)
generate_rss = true     # Generate RSS feed (default: true)
rss_limit = 20          # Number of posts in RSS (default: 20)
generate_sitemap = true # Generate sitemap.xml (default: true)
clean_urls = true       # Use clean URLs (/post instead of /post.html)
include_drafts = false  # Include drafts in build (default: false)

# ===== MARKDOWN SETTINGS =====
[markdown]
enable_tables = true             # Table support
enable_footnotes = true          # Footnote support
enable_strikethrough = true      # Strikethrough support ~~text~~
enable_tasklists = true          # Task list support - [ ] / - [x]
enable_smart_punctuation = true  # Smart punctuation (-- → —, ... → …)
enable_heading_attributes = true # Heading attributes {#id .class}
syntax_highlighting = true       # Syntax highlighting
syntax_theme = "github-dark"     # Highlighting theme (github-dark, github-light)

# ===== CONTENT SETTINGS =====
[content]
enable_smart_quotes = true          # Smart quotes
enable_emoji = true                 # Emoji support :smile:
external_links_new_tab = true       # Open external links in new tab
add_anchor_links = true             # Add anchor links to headings
auto_excerpt = true                 # Automatic post excerpt creation
excerpt_length = 3                  # Number of paragraphs in excerpt (if no separator)
excerpt_separator = "<!-- more -->" # Excerpt separator
reading_speed = 200                 # Reading speed (words per minute)

# ===== RSS SETTINGS =====
[rss]
enabled = true        # Enable RSS generation
limit = 20            # Number of posts in feed
full_content = true   # Include full post content
filename = "feed.xml" # RSS feed filename

# ===== PAGINATION SETTINGS =====
[pagination]
posts_per_page = 10     # Posts per page
pages_in_nav = 5        # Number of pages in navigation
infinite_scroll = false # Infinite scroll

# ===== FEATURES SETTINGS =====
[features]
dark_mode = true           # Dark theme support
light_mode = true          # Light theme support
auto_theme = true          # Automatic theme selection
responsive = true          # Responsive design
seo_optimized = true       # SEO optimization
rss_feed = true            # RSS feed
syntax_highlighting = true # Code highlighting
reading_time = true        # Reading time
social_links = true        # Social links
code_copy = true           # Code copy button
back_to_top = true         # Back to top button
reading_progress = true    # Reading progress

# ===== DATE FORMATS =====
[date_format]
posts = "%d %B %Y"        # Date format in posts (January 15, 2024)
archive = "%d %b"         # Date format in archive (Jan 15)
full = "%d %B %Y в %H:%M" # Full date and time format

# ===== TAXONOMY SETTINGS =====
[taxonomy]
enable_tags = true       # Enable tags
enable_categories = true # Enable categories
min_tag_count = 1        # Minimum tag usage count
max_tags_in_cloud = 50   # Maximum tags in cloud

# ===== DISPLAY SETTINGS =====
[display]
popular_tags_limit = 20 # Number of popular tags
recent_posts_limit = 5  # Number of recent posts
related_posts_limit = 3 # Number of related posts

# ===== MINIMAL CONFIGURATION EXAMPLE =====
# Below is the minimum required set of settings:
#
# [site]
# title = "My Blog"
# description = "Blog description"
# author = "Author"
# base_url = "https://example.com"
#
# [build]
# output_dir = "dist"
# content_dir = "content"
# static_dir = "static"
# templates_dir = "templates"

# Date format reference:
# %Y - year (2024)
# %y - year short (24)
# %B - month full (January)
# %b - month short (Jan)
# %m - month as number (01)
# %d - day (15)
# %H - hour 24h (13)
# %I - hour 12h (01)
# %M - minutes (45)
# %S - seconds (30)
# %p - AM/PM
# %a - weekday short (Mon)
# %A - weekday full (Monday)
