[package]
name = "zahuyach"
version = "0.1.0"
edition = "2024"
description = "Static site generator for blogs written in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/b4rgut/zahuyach"
readme = "README.md"
keywords = ["static-site-generator", "blog", "markdown", "cli"]
categories = ["command-line-utilities", "web-programming"]
authors = ["Aleksey Kalsin <aleksey@kalsin.pro>"]

[dependencies]

[lints.clippy]
# Включаем все группы линтов с правильными приоритетами
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
