jobs:
  # Тэгирование
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semver.outputs.version-string }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: semver
        uses: bitshifted/git-auto-semver@v2
        with:
          create_tag: true
          tag_prefix: "v"

  # Проверка формата и тестов
  check:
    needs: tag
    runs-on: ubuntu-latest
    if: needs.tag.outputs.version != ''
    steps:
      - uses: actions/checkout@v4

      # Установка Rust + кеш
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check
      - run: cargo test --release

  # Публикация
  publish:
    needs: [tag, check]
    runs-on: ubuntu-latest
    if: needs.tag.outputs.version != ''
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
      - run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: git push origin refs/tags/${{ needs.tag.outputs.version }}
