name: Rust CI/CD

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate semantic version
        id: semver
        uses: bitshifted/git-automatic-semantic-versioning@v2
        with:
          create_tag: true
          tag_prefix: "v"

  check:
    name: Format & Test
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - run: cargo fmt --all -- --check
      - run: cargo test --release

  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    needs: [tag, check]
    if: steps.semver.outputs.version-string != ''
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
